# kubectl create secret generic regcred \
#    --from-file=.dockerconfigjson=pullsecret.json \
#    --type=kubernetes.io/dockerconfigjson

apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jq-check
spec:
  runInterval: 15m
  timeout: 2m
  podSpec:
    imagePullSecrets:
      - name: regcred
    containers:
      - env:
          - name: JQ_QUERY
            value: ".status"
          - name: EXPECTED_RESULT
            value: "UP"
          - name: TARGET_URL
            value: "some-rest-api.dev"
          - name: TIMEOUT_DURATION
            value: "5s"
        image: ghcr.io/martinheinz/kuberhealthy-custom-checks/jq-check:latest
        imagePullPolicy: Always
        name: main

# Sample Data:
# {
#   "status": "UP"
# }
